" vImproved!
set nocompatible

" Disable filestype plugin
filetype off

" Setup Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle Bundles
Plugin 'gmarik/Vundle.vim'                 " Manage Plugins

Plugin 'tpope/vim-vinegar'                 " Awesome Netrw
Plugin 'ervandew/supertab'                 " Completion with tab key
Plugin 'christoomey/vim-tmux-navigator'    " Tmux + vim buffer navigation

Plugin 'fatih/vim-go'                      " Awesome Go stuff
Plugin 'othree/html5.vim'                   " HTML5 syntax and completion

Plugin 'morhetz/gruvbox'                   " Pretty colors

" Finish Vundle
call vundle#end()

" Reenable filetype Plugin
filetype plugin indent on

" Color Scheme
colorscheme gruvbox
set background=dark
" Do not use italics
let g:gruvbox_italic=0

" Sensible Defaults
syntax on
set backspace=indent,eol,start
set autochdir
set ruler
set number
set relativenumber
set autoread
set visualbell
set nuw=6
set history=1000
set encoding=utf8
set colorcolumn=80
set previewheight=10
set backupdir=~/.tmp
set directory=~/.tmp
set list listchars=tab:\|\ ,trail:·
set wildignore+=*.o,*.obj,*DS_Store*,tmp/*,*/log/*,.git/*,node_modules/*,.vagrant/*,.tmp/*,.librarian/*,.git*,.ruby-version,*.lock,.bundle/*,.netrwhist

" Netrw
let g:netrw_localrmdir="rm -r"

" Additional Syntax Highlighting
autocmd BufNew,BufRead *.json set ft=javascript
autocmd BufNew,BufRead Podfile set ft=ruby
autocmd BufNew,BufRead Vagrantfile set ft=ruby
autocmd BufNew,BufRead Gemfile set ft=ruby

" Filetypes
augroup snoocfiletypes
  autocmd!
  autocmd FileType vim setlocal ai et sw=2 sts=2 ts=2
  autocmd FileType ruby,eruby setlocal ai et sw=2 sts=2 ts=2
  autocmd FileType javascript setlocal ai et sw=2 sts=2 ts=2
  autocmd FileType php setlocal ai et sw=4 sts=4 ts=4
  autocmd FileType html setlocal ai et sw=4 sts=4 ts=4
  autocmd FileType markdown setlocal ai et sw=4 sts=4 ts=4 tw=80
  autocmd FileType go setlocal ai sw=4 ts=4
augroup END

" Mouse
if has("mouse")
  set mouse=a
  if &term =~ "xterm" || &term =~ "screen"
    set ttymouse=xterm2

    autocmd VimEnter,FocusGained,BufEnter * set ttymouse=xterm2
  endif
endif
