set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-vinegar'

call vundle#end()

filetype plugin indent on

syntax on
set backspace=indent,eol,start
